# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/Files/Code/repos/pyqt-colorpicker-widget/colorpicker/ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

# The original code was edited to better suit this project, it should not be generated again using the .ui file.

from PyQt6 import QtCore, QtWidgets
from PyQt6.QtCore import Qt


class Ui_ColorPicker(object):
    def setupUi(self, ColorPicker):
        ColorPicker.setObjectName("ColorPicker")
        ColorPicker.setSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Expanding)

        self.mainLayout = QtWidgets.QVBoxLayout(ColorPicker)
        self.mainLayout.setContentsMargins(5, 5, 5, 5)
        self.mainLayout.setSpacing(5)
        self.mainLayout.setAlignment(Qt.AlignmentFlag.AlignLeft)
        self.mainLayout.setAlignment(Qt.AlignmentFlag.AlignTop)

        # === Top Row: Preview + Inputs ===
        self.topRow = QtWidgets.QHBoxLayout()

        # Preview block
        self.color_vis = QtWidgets.QLabel()
        self.color_vis.setMinimumSize(QtCore.QSize(100, 70))
        self.color_vis.setStyleSheet("background-color: #000; border: 1px solid #000;")
        self.topRow.addWidget(self.color_vis)

        # Input fields column
        self.inputFields = QtWidgets.QVBoxLayout()

        # RGB Row
        self.rgbRow = QtWidgets.QHBoxLayout()
        self.rgbRow.addWidget(QtWidgets.QLabel("RGB:"))
        self.red = QtWidgets.QLineEdit()
        self.green = QtWidgets.QLineEdit()
        self.blue = QtWidgets.QLineEdit()
        for w in (self.red, self.green, self.blue):
            w.setFixedWidth(40)
            w.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
            self.rgbRow.addWidget(w)
        self.inputFields.addLayout(self.rgbRow)

        # HSV Row
        self.hsvRow = QtWidgets.QHBoxLayout()
        self.hsvRow.addWidget(QtWidgets.QLabel("HSV:"))
        self.hue = QtWidgets.QLineEdit()
        self.saturation = QtWidgets.QLineEdit()
        self.value = QtWidgets.QLineEdit()
        for w in (self.hue, self.saturation, self.value):
            w.setFixedWidth(40)
            w.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
            self.hsvRow.addWidget(w)
        self.inputFields.addLayout(self.hsvRow)

        # HEX Row
        self.hexRow = QtWidgets.QHBoxLayout()
        self.hexRow.addWidget(QtWidgets.QLabel("HEX:"))
        self.hex = QtWidgets.QLineEdit()
        self.hex.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.hex.setFixedWidth(80)
        self.hexRow.addWidget(self.hex)
        self.inputFields.addLayout(self.hexRow)

        self.topRow.addLayout(self.inputFields)
        self.mainLayout.addLayout(self.topRow)

        # === Bottom Row: Color Pad + Hue Slider ===
        self.bottomRow = QtWidgets.QHBoxLayout()
        self.bottomRow.setContentsMargins(0, 5, 5, 5)
        self.bottomRow.setAlignment(Qt.AlignmentFlag.AlignTop)

        # Color area frame
        self.color_view = QtWidgets.QFrame()
        self.color_view.setFixedSize(QtCore.QSize(ColorPicker.width, ColorPicker.height))
        self.color_view.setStyleSheet("background: qlineargradient(x1:1, x2:0, stop:0 hsl(0%,100%,50%), stop:1 white);")
        self.color_view.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)

        self.black_overlay = QtWidgets.QFrame(self.color_view)
        self.black_overlay.setGeometry(QtCore.QRect(0, 0, ColorPicker.width, ColorPicker.height))
        self.black_overlay.setStyleSheet("background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0,0,0,0), stop:1 black);")

        self.selector = QtWidgets.QFrame(self.black_overlay)
        self.selector.setGeometry(QtCore.QRect(100, 100, 12, 12))
        self.selector.setStyleSheet("border: 2px solid white; border-radius: 6px; background: none;")

        self.bottomRow.addWidget(self.color_view)

        # Hue slider
        self.hue_slider = QtWidgets.QFrame()
        self.hue_slider.setFixedSize(QtCore.QSize(30, ColorPicker.height))
        self.hue_slider.setStyleSheet("background: qlineargradient(y1:1, y2:0, stop:0 red, stop:0.17 yellow, stop:0.33 green, stop:0.5 cyan, stop:0.66 blue, stop:0.83 magenta, stop:1 red);")
        self.bottomRow.addWidget(self.hue_slider)

        # Hue Selector Overlay
        self.hue_selector = QtWidgets.QLabel(self.hue_slider)
        self.hue_selector.setGeometry(QtCore.QRect(0, 0, 26, 15))
        self.hue_selector_width = 26
        self.hue_selector.setStyleSheet("background-color: #222; border: 1px solid white; border-radius: 3px;")
        self.hue_selector.setObjectName("hue_selector")

        self.bottomWidget = QtWidgets.QWidget()
        self.bottomWidget.setSizePolicy(
            QtWidgets.QSizePolicy.Policy.Fixed,
            QtWidgets.QSizePolicy.Policy.Expanding
        )
        self.bottomWidget.setContentsMargins(0, 0, 0, 0)
        self.bottomWidget.setLayout(self.bottomRow)
        self.mainLayout.addWidget(self.bottomWidget)

        # === Tab Order & Object Names ===
        self.red.setObjectName("red")
        self.green.setObjectName("green")
        self.blue.setObjectName("blue")
        self.hue.setObjectName("hue")
        self.saturation.setObjectName("saturation")
        self.value.setObjectName("value")
        self.hex.setObjectName("hex")

        QtCore.QMetaObject.connectSlotsByName(ColorPicker)
