# Form implementation generated from reading ui file 'ui/main_window.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 500)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.loadButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.loadButton.setObjectName("loadButton")
        self.verticalLayout.addWidget(self.loadButton)
        self.imageLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.imageLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.imageLabel.setScaledContents(False)
        self.imageLabel.setMinimumSize(QtCore.QSize(200, 200))
        self.imageLabel.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.imageLabel.setObjectName("imageLabel")
        self.verticalLayout.addWidget(self.imageLabel)
        self.hboxlayout = QtWidgets.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        self.zoomLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.zoomLabel.setObjectName("zoomLabel")
        self.hboxlayout.addWidget(self.zoomLabel)
        self.zoomSlider = QtWidgets.QSlider(parent=self.centralwidget)
        self.zoomSlider.setMinimum(1)
        self.zoomSlider.setMaximum(40)
        self.zoomSlider.setProperty("value", 20)
        self.zoomSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.zoomSlider.setTickInterval(1)
        self.zoomSlider.setTickPosition(QtWidgets.QSlider.TickPosition.TicksBelow)
        self.zoomSlider.setObjectName("zoomSlider")
        self.hboxlayout.addWidget(self.zoomSlider)
        self.verticalLayout.addLayout(self.hboxlayout)
        self.verticalLayout.setStretch(1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Pixel Art Color Processor"))
        self.loadButton.setText(_translate("MainWindow", "Load Image"))
        self.imageLabel.setText(_translate("MainWindow", "[ Image will appear here ]"))
        self.zoomLabel.setText(_translate("MainWindow", "100%"))
